### ISSUE TITLE
L_d, L_q calculation questions

### ISSUE THREAD

**Issue by sasupe** [TUMFTM/Electric_Machine_Design#2]
Hi Svenja and Team,

In the below lines, why is Ld, Lq recalculated in L1303 and L1304

https://github.com/TUMFTM/Electric_Machine_Design/blob/e9bb513b39edc4860a797d589aa221eccc39051a/PMSM%20Tool/Auslegung_PMSM.m#L1299-L1304

Thanks

**Comment by SvenjaKalt** [comment]
Hello Sasupe,
thank you for your message.
it is recaluculated according to the formula in the source "Müller08" - https://books.google.de/books/about/Berechnung_elektrischer_Maschinen.html?id=G2OOvMZksSwC&redir_esc=y
it is redundant and could be omitted thou you are correct.
best regards,
Svenja
